# 1.2 Ejercicio 1.2
En este repo: https://github.com/woodnathan/MarioKart8-Stats hay datasets sobre los stats de los personajes, vehıculos, alas y neumaticos del Mario Kart 8. Responder, utilizando estos datasets, las siguientes preguntas.  
a) ¿Cuales son los personajes con mejor stat de velocidad?  
b) ¿Cuantas posibles combinaciones de personaje-vehiculo-neumaticos-ala se pueden armar?

**Importo la biblioteca Pandas**

In [1]:
import pandas as pd

**Busco en el repositorio los URL de los raw csv**

In [2]:
url_vehiculos = 'https://raw.githubusercontent.com/woodnathan/MarioKart8-Stats/master/bodies.csv'

In [3]:
url_personajes = 'https://raw.githubusercontent.com/woodnathan/MarioKart8-Stats/master/characters.csv'

In [4]:
url_neumaticos = 'https://raw.githubusercontent.com/woodnathan/MarioKart8-Stats/master/tires.csv'

In [5]:
url_alas = 'https://raw.githubusercontent.com/woodnathan/MarioKart8-Stats/master/gliders.csv'

**Obtengo los dataframes de vehiculos, personajes, neumaticos y alas**

In [6]:
vehiculos = pd.read_csv(url_vehiculos, error_bad_lines=False)

In [7]:
personajes = pd.read_csv(url_personajes, error_bad_lines=False)

In [8]:
neumaticos = pd.read_csv(url_neumaticos, error_bad_lines=False)

In [9]:
alas = pd.read_csv(url_alas, error_bad_lines=False)

**Muestro las primeras cinco filas de los dataframes para visualizarlos**

In [10]:
vehiculos.head()

,Type,Body,Speed,Speed (Water),Speed (Air),Speed (Ground),Acceleration,Weight,Handling,Handling (Water),Handling (Air),Handling(Ground),Traction,Mini Turbo
0,Kart,Standard Kart,0.0,0.00,-0.25,0.25,0.00,0.00,0.0,0.0,-0.25,0.25,0.0,0.0
1,Kart,Prancer,0.0,0.00,-0.25,0.25,0.00,0.00,0.0,0.0,-0.25,0.25,0.0,0.0
2,Kart,Cat Cruiser,0.0,0.00,-0.25,0.25,0.00,0.00,0.0,0.0,-0.25,0.25,0.0,0.0
3,Kart,Sneeker,0.0,0.00,-0.25,0.25,0.00,0.00,0.0,0.0,-0.25,0.25,0.0,0.0
4,Kart,Gold Standard,0.5,0.25,0.25,0.00,-0.25,0.25,0.0,0.0,-0.25,0.00,-1.0,-0.5

In [11]:
personajes.head()

,Class,Character,Speed,Speed (Water),Speed (Air),Speed (Ground),Acceleration,Weight,Handling,Handling (Water),Handling (Air),Handling(Ground),Traction,Mini Turbo
0,Light,Baby Mario,2.25,2.25,2.25,2.25,3.25,2.25,4.75,4.75,4.75,4.75,4.5,3.0
1,Light,Baby Luigi,2.25,2.25,2.25,2.25,3.25,2.25,4.75,4.75,4.75,4.75,4.5,3.0
2,Light,Baby Peach,2.25,2.25,2.25,2.25,3.25,2.25,4.75,4.75,4.75,4.75,4.5,3.0
3,Light,Baby Daisy,2.25,2.25,2.25,2.25,3.25,2.25,4.75,4.75,4.75,4.75,4.5,3.0
4,Light,Baby Rosalina,2.25,2.25,2.25,2.25,3.25,2.25,4.75,4.75,4.75,4.75,4.5,3.0

In [12]:
neumaticos.head()

,Type,Body,Speed,Speed (Water),Speed (Air),Speed (Ground),Acceleration,Weight,Handling,Handling (Water),Handling (Air),Handling(Ground),Traction,Mini Turbo
0,NaN,Standard,0.0,0.5,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1,NaN,Blue Standard,0.0,0.5,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0
2,NaN,Offroad,0.0,0.5,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0
3,NaN,Retro Offroad,0.0,0.5,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0
4,NaN,Monster,0.0,0.0,0.0,-0.5,0.0,-0.5,-0.75,-0.75,-0.75,-0.75,0.75,0.0

In [13]:
alas.head()

,Type,Body,Speed,Speed (Water),Speed (Air),Speed (Ground),Acceleration,Weight,Handling,Handling (Water),Handling (Air),Handling(Ground),Traction,Mini Turbo
0,Speed,Super,0,0,0.25,0,0.0,0.0,0,0,0.0,0,0,0.0
1,Speed,Waddle Wing,0,0,0.25,0,0.0,0.0,0,0,0.0,0,0,0.0
2,Speed,Plane,0,0,0.25,0,0.0,0.0,0,0,0.0,0,0,0.0
3,Speed,Wario Wing,0,0,0.25,0,0.0,0.0,0,0,0.0,0,0,0.0
4,Speed,Gold,0,0,0.25,0,0.0,0.0,0,0,0.0,0,0,0.0

**a) ¿Cuales son los personajes con mejor stat de velocidad?**

In [14]:
personajes[personajes['Speed'] == personajes['Speed'].max()].Character

28           Wario
29          Bowser
30    Morton Koopa
31       Mii Heavy
Name: Character, dtype: object

**b) ¿Cuantas posibles combinaciones de personaje-vehiculo-neumaticos-ala se pueden armar?**

In [15]:
cantidadDeCombinacionesPosibles = len(personajes)*len(vehiculos)*len(neumaticos)*len(alas)
print(cantidadDeCombinacionesPosibles)

144000